### ISSUE TITLE
Cannot choose width and height  independently from each other

### ISSUE THREAD

**Issue by gastonsimone** [adrienverge/PhotoCollage#23]
Thanks for this application. It is really good and useful! I just found one issue when using it.
Using from commit e2d61fcf6c24c38cb693fde143b54c5dcdf6e31e (Sun Nov 22).
Save poster dialog shows the Poster height field disabled, so I cannot freely choose the dimensions of the final image. Is it possible to choose width and height independently from each other?
Thanks!

**Comment by adrienverge** [comment]
Thanks @gastonsimone!

Unfortunately what you're asking is not possible, because the width / height ratio is determined by the input images. You can only adjust is the *scale* (both `w` and `h`) by setting the output width.

However, you can influence the placement algorithm to force a *thicker* (or *taller*) image by using the two buttons with arrows.

**Comment by gastonsimone** [comment]
Thanks for the reply, Adrien!
That's a pity. I was hoping I could get rid of Picasa with this tool, where I can freely choose the dimensions of the final picture. I need to create a collage in A4 paper size.
Anyway, thanks a lot.

**Comment by ojob** [comment]
@gastonsimone Seems to me that current version allows a free ratio between width and height.

**Comment by gastonsimone** [comment]
Thanks for letting me know, @ojob! I will take a look again.
