### ISSUE TITLE
Drag&Drop

### ISSUE THREAD

**Issue by rollsappletree** [adrienverge/PhotoCollage#6]
More than an issue is a feature request:
would be nice if it work with Drag & Drop images from nautilus itself into the "poster area".

Thanks,
C

**Comment by adrienverge** [comment]
Great idea Carmelo! Just done. :-)

**Comment by lukacu** [comment]
A small comment regarding drag&drop feature. At the moment the dropped images always form a new collage. I have a small fix that enables appending of new images to existing collage by default, but I wanted to ask first if this "new collage" is desired behavior or can we have both?

**Comment by adrienverge** [comment]
Being able to add/remove photos from the current collage would clearly be a nice feature (and could replace the old "restart from scratch when drag&drop").

But it raises an issue: currently, the `photolist` array is global, and not updated when going back in history. So if an user (a) creates a 1-photo collage, then (b) creates a new 8-photo collage, (c) goes back in history to collage #1, (d) adds or removes a photo, this latter photo will be added/removed from the 8-photo list (instead of the collage #1, as he/she would expect).

This unwanted behavior should be overcomed before adding the feature you propose. And maybe just replicating `photolist` for each new history element will be sufficient. What do you think?

**Comment by lukacu** [comment]
Yes, I have noticed that the solution is not as straightforward as I have first thought. I did a simple hack that appended new images to `photolist` as a temporary fix. I think that removing global `photolist` would be one way of doing it since images are stored in the `Page` object anyway. If I find a better solution I will mention it here.

**Comment by adrienverge** [comment]
Hi lukacu, I have set `photolist` local to each element in history, so we don't have this problem anymore. I also changed the default behavior, that is to add photos instead of replacing them all. If you want to test it, it's in a new branch `add_or_remove_photos`.

I also plan to add small X icons to remove photos before merging this branch into `master`.

**Comment by lukacu** [comment]
Great, I have tested branch with a few photos and so far everything works. The empty page icon is also informative :)
